[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.next-devtools]
command = "npx"
args = [
    "-y",
    "next-devtools-mcp@latest",
]
