export const BERAS_BREAKPOINTS = Object.freeze({
  narrow: 320,
  tablet: 768,
  desktop: 1024,
  wide: 1440,
});

export type BerasVariant = 'solid' | 'soft' | 'outline' | 'ghost';
export type BerasSize = 'sm' | 'md' | 'lg';
export type BerasTone = 'brand' | 'neutral' | 'info' | 'success' | 'warning' | 'danger';

export const berasLightTokenReference = Object.freeze({
  '--beras-color-page': { value: '#f2f4f9', group: 'color', description: 'Application page canvas.' },
  '--beras-color-surface': { value: '#ffffff', group: 'color', description: 'Primary raised surface.' },
  '--beras-color-surface-subtle': { value: '#f8fafc', group: 'color', description: 'Quiet nested surface.' },
  '--beras-color-text': { value: '#011d4d', group: 'color', description: 'Default text and heading color.' },
  '--beras-color-text-muted': { value: '#475569', group: 'color', description: 'Secondary text.', note: 'Contrast-corrected from Tere light #9ca3af for WCAG AA on white.' },
  '--beras-color-border': { value: '#d5dce8', group: 'color', description: 'Default control and surface border.' },
  '--beras-color-brand': { value: '#0f718e', group: 'color', description: 'Brand action and emphasis.', note: 'Contrast-corrected from Tere accent #1282a2 for WCAG AA text on white.' },
  '--beras-color-brand-hover': { value: '#034078', group: 'color', description: 'Brand hover and active emphasis.' },
  '--beras-color-focus': { value: '#0b657b', group: 'color', description: 'Keyboard focus indicator.', note: 'Contrast-corrected from Tere accent-light #22b8d4 for 3:1 UI contrast.' },
  '--beras-color-overlay': { value: 'rgb(1 29 77 / 0.64)', group: 'color', description: 'Modal backdrop.' },

  '--beras-status-success-foreground': { value: '#047857', group: 'status', description: 'Success text and icon.' },
  '--beras-status-success-background': { value: '#ecfdf5', group: 'status', description: 'Success surface.' },
  '--beras-status-success-border': { value: '#6ee7b7', group: 'status', description: 'Success boundary.' },
  '--beras-status-warning-foreground': { value: '#92400e', group: 'status', description: 'Warning text and icon.' },
  '--beras-status-warning-background': { value: '#fffbeb', group: 'status', description: 'Warning surface.' },
  '--beras-status-warning-border': { value: '#f59e0b', group: 'status', description: 'Warning boundary.' },
  '--beras-status-danger-foreground': { value: '#b91c1c', group: 'status', description: 'Danger text and icon.' },
  '--beras-status-danger-background': { value: '#fef2f2', group: 'status', description: 'Danger surface.' },
  '--beras-status-danger-border': { value: '#fca5a5', group: 'status', description: 'Danger boundary.' },
  '--beras-status-info-foreground': { value: '#1d4ed8', group: 'status', description: 'Information text and icon.' },
  '--beras-status-info-background': { value: '#eff6ff', group: 'status', description: 'Information surface.' },
  '--beras-status-info-border': { value: '#93c5fd', group: 'status', description: 'Information boundary.' },
  '--beras-status-neutral-foreground': { value: '#475569', group: 'status', description: 'Neutral text and icon.' },
  '--beras-status-neutral-background': { value: '#f1f5f9', group: 'status', description: 'Neutral surface.' },
  '--beras-status-neutral-border': { value: '#cbd5e1', group: 'status', description: 'Neutral boundary.' },

  '--beras-data-1': { value: '#1282a2', group: 'data', description: 'Ordered categorical series 1; pair with a label or marker.' },
  '--beras-data-2': { value: '#7c3aed', group: 'data', description: 'Ordered categorical series 2; pair with a label or marker.' },
  '--beras-data-3': { value: '#047857', group: 'data', description: 'Ordered categorical series 3; pair with a label or marker.' },
  '--beras-data-4': { value: '#b91c1c', group: 'data', description: 'Ordered categorical series 4; pair with a label or marker.' },
  '--beras-data-5': { value: '#b45309', group: 'data', description: 'Ordered categorical series 5; pair with a label or marker.' },
  '--beras-data-6': { value: '#034078', group: 'data', description: 'Ordered categorical series 6; pair with a label or marker.' },
  '--beras-data-7': { value: '#be185d', group: 'data', description: 'Ordered categorical series 7; pair with a label or marker.' },
  '--beras-data-8': { value: '#22b8d4', group: 'data', description: 'Ordered categorical series 8; decorative alone, otherwise pair with a label or marker.' },
  '--beras-data-grid': { value: '#dbe2ea', group: 'data', description: 'Chart grid line.' },
  '--beras-data-axis': { value: '#475569', group: 'data', description: 'Chart axis and tick label.' },
  '--beras-data-tooltip': { value: '#011d4d', group: 'data', description: 'Chart tooltip surface.' },

  '--beras-font-sans': { value: "var(--font-space-grotesk, 'Space Grotesk'), 'Space Grotesk', ui-sans-serif, system-ui, sans-serif", group: 'typography', description: 'Space Grotesk with system fallback.' },
  '--beras-font-mono': { value: "var(--font-ibm-plex-mono, 'IBM Plex Mono'), 'IBM Plex Mono', ui-monospace, 'SFMono-Regular', Consolas, monospace", group: 'typography', description: 'IBM Plex Mono with system fallback.' },
  '--beras-font-size-xs': { value: '0.75rem', group: 'typography', description: 'Compact supporting text.' },
  '--beras-font-size-sm': { value: '0.875rem', group: 'typography', description: 'Small body text.' },
  '--beras-font-size-md': { value: '1rem', group: 'typography', description: 'Default body text.' },
  '--beras-font-size-lg': { value: '1.125rem', group: 'typography', description: 'Lead text.' },
  '--beras-font-size-xl': { value: '1.5rem', group: 'typography', description: 'Section heading.' },
  '--beras-font-size-2xl': { value: '2rem', group: 'typography', description: 'Page heading.' },
  '--beras-line-height-tight': { value: '1.25', group: 'typography', description: 'Compact display line height.' },
  '--beras-line-height-base': { value: '1.5', group: 'typography', description: 'Default readable line height.' },
  '--beras-line-height-relaxed': { value: '1.75', group: 'typography', description: 'Long-form line height.' },
  '--beras-font-weight-regular': { value: '400', group: 'typography', description: 'Space Grotesk and IBM Plex Mono regular weight.' },
  '--beras-font-weight-medium': { value: '500', group: 'typography', description: 'Space Grotesk and IBM Plex Mono medium weight.' },
  '--beras-font-weight-semibold': { value: '600', group: 'typography', description: 'Space Grotesk and IBM Plex Mono semibold weight.' },
  '--beras-font-weight-bold': { value: '700', group: 'typography', description: 'Space Grotesk and IBM Plex Mono bold weight.' },

  '--beras-space-0': { value: '0', group: 'spacing', description: 'Zero spacing.' },
  '--beras-space-1': { value: '0.25rem', group: 'spacing', description: '4px base spacing step.' },
  '--beras-space-2': { value: '0.5rem', group: 'spacing', description: '8px spacing step.' },
  '--beras-space-3': { value: '0.75rem', group: 'spacing', description: '12px spacing step.' },
  '--beras-space-4': { value: '1rem', group: 'spacing', description: '16px spacing step.' },
  '--beras-space-5': { value: '1.25rem', group: 'spacing', description: '20px spacing step.' },
  '--beras-space-6': { value: '1.5rem', group: 'spacing', description: '24px spacing step.' },
  '--beras-space-8': { value: '2rem', group: 'spacing', description: '32px spacing step.' },
  '--beras-space-10': { value: '2.5rem', group: 'spacing', description: '40px spacing step.' },
  '--beras-space-12': { value: '3rem', group: 'spacing', description: '48px spacing step.' },
  '--beras-space-16': { value: '4rem', group: 'spacing', description: '64px spacing step.' },
  '--beras-control-height-sm': { value: '2rem', group: 'sizing', description: 'Small control height.' },
  '--beras-control-height-md': { value: '2.5rem', group: 'sizing', description: 'Default control height.' },
  '--beras-control-height-lg': { value: '3rem', group: 'sizing', description: 'Large control height.' },
  '--beras-content-width': { value: '72rem', group: 'sizing', description: 'Default content width.' },
  '--beras-content-max-width': { value: '90rem', group: 'sizing', description: 'Wide content maximum.' },
  '--beras-sidebar-width': { value: '15.75rem', group: 'sizing', description: 'Desktop sidebar width.' },
  '--beras-topbar-height': { value: '4rem', group: 'sizing', description: 'Application topbar height.' },

  '--beras-border-width': { value: '1px', group: 'border', description: 'Default boundary width.' },
  '--beras-border-width-strong': { value: '2px', group: 'border', description: 'Emphasized boundary width.' },
  '--beras-radius-sm': { value: '0.25rem', group: 'radius', description: 'Compact radius.' },
  '--beras-radius-md': { value: '0.5rem', group: 'radius', description: 'Default radius.' },
  '--beras-radius-lg': { value: '0.75rem', group: 'radius', description: 'Raised surface radius.' },
  '--beras-radius-full': { value: '9999px', group: 'radius', description: 'Pill or circular radius.' },
  '--beras-shadow-sm': { value: '0 1px 2px rgb(1 29 77 / 0.08)', group: 'elevation', description: 'Subtle raised edge.' },
  '--beras-shadow-md': { value: '0 8px 24px rgb(1 29 77 / 0.12)', group: 'elevation', description: 'Popover elevation.' },
  '--beras-shadow-lg': { value: '0 20px 48px rgb(1 29 77 / 0.16)', group: 'elevation', description: 'Drawer elevation.' },
  '--beras-shadow-overlay': { value: '0 24px 64px rgb(1 29 77 / 0.22)', group: 'elevation', description: 'Dialog elevation.' },

  '--beras-duration-fast': { value: '120ms', group: 'motion', description: 'Immediate interaction duration.' },
  '--beras-duration-base': { value: '200ms', group: 'motion', description: 'Default transition duration.' },
  '--beras-duration-slow': { value: '320ms', group: 'motion', description: 'Large-surface transition duration.' },
  '--beras-ease-standard': { value: 'cubic-bezier(0.2, 0, 0, 1)', group: 'motion', description: 'Default easing curve.' },
  '--beras-ease-emphasized': { value: 'cubic-bezier(0.2, 0, 0, 1.2)', group: 'motion', description: 'Emphasized entrance curve.' },

  '--beras-layer-base': { value: '0', group: 'layer', description: 'Normal document layer.' },
  '--beras-layer-sticky': { value: '100', group: 'layer', description: 'Sticky controls.' },
  '--beras-layer-dropdown': { value: '200', group: 'layer', description: 'Dropdown and popover.' },
  '--beras-layer-drawer': { value: '300', group: 'layer', description: 'Modal drawer.' },
  '--beras-layer-dialog': { value: '400', group: 'layer', description: 'Modal dialog.' },
  '--beras-layer-toast': { value: '500', group: 'layer', description: 'Toast viewport.' },

  '--beras-breakpoint-narrow': { value: '320px', group: 'breakpoint', description: 'Narrow evidence width.' },
  '--beras-breakpoint-tablet': { value: '768px', group: 'breakpoint', description: 'Tablet evidence width and CSS boundary.' },
  '--beras-breakpoint-desktop': { value: '1024px', group: 'breakpoint', description: 'Desktop shell CSS boundary.' },
  '--beras-breakpoint-wide': { value: '1440px', group: 'breakpoint', description: 'Wide evidence width and CSS boundary.' },
});

type BerasTokenName = keyof typeof berasLightTokenReference;

export const BERAS_TOKEN_NAMES = Object.freeze(
  Object.keys(berasLightTokenReference) as BerasTokenName[],
);
